apiVersion: 1

datasources:
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    url: http://prometheus:9090
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true

  - name: Prometheus AlertManager
    type: camptocamp-prometheus-alertmanager-datasource
    access: proxy
    url: http://alertmanager:9093
    editable: false
    isDefault: false